services:
  qbittorrent:
    image: qiyuey/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
      - UT=true
    volumes:
      - /share/Public/Docker/qbittorrent:/config
      - /share/Public/Download:/downloads
      - /share/Public/Tech:/cert
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6363:6363
    restart: unless-stopped
