name: Manual Build Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - './ReleaseTag'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4
      
      # 设置 QEMU
      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3
      
      # 设置 Docker Buildx
      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录到 Docker Hub
      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 获得仓库中的ReleaseTag
      - name: Set Version
        id: set-version
        run: |
          echo "version=$(cat ReleaseTag | head -n1)" >> $GITHUB_OUTPUT
          echo "ReleaseTag=$(cat ReleaseTag | head -n1)" 
          echo "status=success" >> $GITHUB_OUTPUT

      # Build and push
      - name: Build and push
        if: steps.set-version.outputs.status == 'success'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            qiyuey/qbittorrent:${{ steps.set-version.outputs.version }}
            qiyuey/qbittorrent:latest
