name: Pull Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '15 19 * * *'

jobs:
  pull-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: Pull upstream changes
        run: |
          git remote add upstream https://github.com/SuperNG6/docker-qbittorrent.git
          git config --global user.email "1123274330@qq.com"
          git config --global user.name "yuchuan"
          git fetch upstream
          git rebase upstream/master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
